version: '3'
services:
  mongo:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    restart: unless-stopped
    build: .
    env_file: ./.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/sw
    ports:
      - $PORT:3001
    volumes:
      - ./:/code
volumes:
  db: